// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(BackendApiContext))]
    partial class BackendApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Models.BusinessContactDetails", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.ToTable("BusinessContactDetails");

                    b.HasData(
                        new
                        {
                            ContactID = 1,
                            Address = "16th Court Dr",
                            City = "Olympia",
                            ContactName = "Rogger",
                            Country = "US",
                            Phone = "222-555-6666",
                            PostalCode = "98501"
                        },
                        new
                        {
                            ContactID = 2,
                            Address = "16th Court Dr",
                            City = "Olympia",
                            ContactName = "Alice",
                            Country = "US",
                            Phone = "222-555-6666",
                            PostalCode = "98501"
                        },
                        new
                        {
                            ContactID = 3,
                            Address = "16th Court Dr",
                            City = "Olympia",
                            ContactName = "Bob",
                            Country = "US",
                            Phone = "222-555-6666",
                            PostalCode = "98501"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.DynamicContent", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("DynamicContent");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Author = "Robert",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tincidunt nibh et nulla pharetra, id euismod velit scelerisque. Ut maximus dui et sem suscipit, a feugiat nisl gravida. Mauris id eros sit amet diam sollicitudin interdum nec at nisl. In ac tortor purus. Sed scelerisque imperdiet lorem in rutrum.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What does the fox say?"
                        },
                        new
                        {
                            PostId = 2,
                            Author = "Dillon",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tincidunt nibh et nulla pharetra, id euismod velit scelerisque. Ut maximus dui et sem suscipit, a feugiat nisl gravida. Mauris id eros sit amet diam sollicitudin interdum nec at nisl. In ac tortor purus. Sed scelerisque imperdiet lorem in rutrum.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top 10 Chess Duels"
                        },
                        new
                        {
                            PostId = 3,
                            Author = "Tyler",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tincidunt nibh et nulla pharetra, id euismod velit scelerisque. Ut maximus dui et sem suscipit, a feugiat nisl gravida. Mauris id eros sit amet diam sollicitudin interdum nec at nisl. In ac tortor purus. Sed scelerisque imperdiet lorem in rutrum.",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Basketball Top Basket"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.FeedbackData", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Blogger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackId");

                    b.ToTable("FeedbackData");

                    b.HasData(
                        new
                        {
                            FeedbackId = 1,
                            Blogger = "Tyler",
                            Feedback = "Robert",
                            PublishDate = "11-15-22"
                        },
                        new
                        {
                            FeedbackId = 2,
                            Blogger = "Alice",
                            Feedback = "Donald",
                            PublishDate = "11-15-22"
                        },
                        new
                        {
                            FeedbackId = 3,
                            Blogger = "Devin",
                            Feedback = "Rogger",
                            PublishDate = "11-15-22"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.StaticContent", b =>
                {
                    b.Property<int>("ContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentID"));

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContentID");

                    b.ToTable("StaticContent");

                    b.HasData(
                        new
                        {
                            ContentID = 1,
                            Product = "Snuggy",
                            ProductDes = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tincidunt nibh et nulla pharetra, id euismod velit scelerisque. Ut maximus dui et sem suscipit, a feugiat nisl gravida. Mauris id eros sit amet diam sollicitudin interdum nec at nisl. In ac tortor purus. Sed scelerisque imperdiet lorem in rutrum.",
                            Seller = "Donald"
                        },
                        new
                        {
                            ContentID = 2,
                            Product = "Chess",
                            ProductDes = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tincidunt nibh et nulla pharetra, id euismod velit scelerisque. Ut maximus dui et sem suscipit, a feugiat nisl gravida. Mauris id eros sit amet diam sollicitudin interdum nec at nisl. In ac tortor purus. Sed scelerisque imperdiet lorem in rutrum.",
                            Seller = "Randy"
                        },
                        new
                        {
                            ContentID = 3,
                            Product = "Basketball",
                            ProductDes = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tincidunt nibh et nulla pharetra, id euismod velit scelerisque. Ut maximus dui et sem suscipit, a feugiat nisl gravida. Mauris id eros sit amet diam sollicitudin interdum nec at nisl. In ac tortor purus. Sed scelerisque imperdiet lorem in rutrum.",
                            Seller = "Tyson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
